### ISSUE TITLE
Write unit tests for converting simple BrApi JSON data model definitions

### ISSUE THREAD

**Issue by asishallab** [LzLang/Zendro-Converter#2]
Use a simple BrApi JSON data model definition. You can write one yourself or use a simple model like `study`.

_Manually_ generate the corresponding Zendro input data model definition. In this first iteration make sure that all supported properties (fields) get translated correctly.

Use a unit test to ensure that your translation code generates the expected output.

**Comment by asishallab** [comment]
If necessary, extend your code so that it generates valid JSON data model definitions for Zendro. Currently, it seams, your code generates text-output only.

**Comment by LzLang** [comment]
> Use a simple BrApi JSON data model definition. You can write one yourself or use a simple model like `study`.
> 
> _Manually_ generate the corresponding Zendro input data model definition. In this first iteration make sure that all supported properties (fields) get translated correctly.
> 
> Use a unit test to ensure that your translation code generates the expected output.

I plan for the next version (v0.0.7) to test different input files and create a unit test to test my code.
At least in the current version with `study` as input the scripts seems to work fine but further testing is still needed.



> If necessary, extend your code so that it generates valid JSON data model definitions for Zendro. Currently, it seams, your code generates text-output only.

The current version is already generating a json output.
This was not apparent due to the structure of the Github repository.
I have revised the repository and put old outputs in a separate folder, so the "results" folder only contains outputs corresponding to the version.

In the current version (convert v0.0.6) only one input file at a time can be used.
For version 0.0.8 I plan to automate the process:
- Instead of one input file only the path to BrAPI folder
- Script searches automatically for json files and creates a identical structur in the result folder
- Opens every found json files and generates a output in the corresponding results folder

**Comment by LzLang** [comment]
A first Unit-Test is now available.
Until now it's just a simple test, but for the future it's planed, that they will become more complex.
