### ISSUE TITLE
Setup a Zendro BrApi warehouse with the translated data models

### ISSUE THREAD

**Issue by asishallab** [LzLang/Zendro-Converter#6]
Once the new arguments have been implemented. Read through the quickstart guide of Zendro and setup a Zendro warehouse for your translated data models. 

Recommendations:
- use a _native_ Linux platform, e.g. a Debian based Linux like Ubuntu (dual-boot should be best)
- use the Dockerized setup of Zendro
- the rest should be a breeze, hopefully

Questions to answer (experiments):
- Do the translated data models work with Zendro?
- Can you start and use a Zendro BrApi warehouse for them?

**Comment by LzLang** [comment]
While setting up the warehouse, I ran into different errors, but luckily I got it to work in the end.

>Do the translated data models work with Zendro?

>Can you start and use a Zendro BrApi warehouse for them?

Yes, the translated data models work with Zendro, but I couldn't test Relationships so far, because of computer issues.
I will try again and will document everything in the Readme, once I update it.
