### ISSUE TITLE
Global project goals

### ISSUE THREAD

**Issue by asishallab** [LzLang/Zendro-Converter#7]
# Global goals

Here, we list and define global goals to help manage this student project. 

* Ensure the translated Zendro data model definitions actually work with Zendro. This means we can create a Zendro data warehouse from these translations without the need to edit any of the translated models.
* We get identifiers for all models, which can be the internal default identifiers
* We have support for different storage types
* We have support for custom identifiers and custom id-types (i.e. `String`)

Depending of how we progress with open questions (#4):
* Exclude some not needed properties.
* Model associations between data models, if readable from some input.

Latest this project active programming terminates mid august.

**Comment by LzLang** [comment]
> Ensure the translated Zendro data model definitions actually work with Zendro. This means we can create a Zendro data warehouse from these translations without the need to edit any of the translated models.

In the past versions, the translated data models worked with Zendro.

> We get identifiers for all models, which can be the internal default identifiers

As default the primary key is named after the model, but you can change/define it with command line arguments


> We have support for different storage types

Currently, the converter supports all of Zendro supported storage types.

> We have support for custom identifiers and custom id-types (i.e. String)

Like in Zendro defined, we support currently `String` and `Int` as id-types with `Int` as default type.
In later versions, we may integreate other/custom types.

> Exclude some not needed properties.

We have to talk about this point and review, which properties are not needed.
Currently, all properties are integrated/converted which are not of type "array" or "object".

> Model associations between data models, if readable from some input.

Associations are integrated, due to some computer issues I couldn't test it so far.
Except of 3 Associations (association to an array, which are currently not supported) are all Associations integrated.
